name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
      - master # Fallback in case your default branch is named master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Point this to where your index.html is located
          path: './aryanandan@mulearn/Task-3/' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
